# name of the workflows/pipeline 
name: github action demo pipeline

# trigger event
on: 
    push: 
        branches:
        - main

jobs:
    demo-jobs:
         runs-on:  ubuntu-latest

         steps:
            - name: checkout code
              uses: actions/checkout@v2
           
            - name:  print message
              run:  echo "welcome github actions"
